<?php
/*
 * @file
 * Install, update, and uninstall functions for the anagrafica module.
 */


/**
 * Implementation of hook_schema().
 */
function italy_schema() {
  $schema = array();
  $schema['italy_province'] = array(
    'fields' => array(
      //indici
      'id_provincia'          => array('type' => 'serial' , 'unsigned' => TRUE, 'not null' => TRUE),
      'id_regione' => array('type' => 'int', 'not null' => TRUE,),
      'provincia'    => array('type' => 'varchar', 'length' => 28,'not null'   => TRUE, 'default' => ''),
      'targa'         => array('type' => 'varchar', 'length' => 2,'not null'   => TRUE, 'default' => ''),
    ),
    'primary key' => array('id_provincia'),
    'indexes' => array(array('id_regione'))
  );

  $schema['italy_regioni'] = array(
    'fields' => array(
      //indici
      'id_regione'          => array('type' => 'serial' , 'unsigned' => TRUE, 'not null' => TRUE),
      'regione'      => array('type' => 'varchar', 'length' => 100,'not null' => TRUE, 'default' => ''),

    ),
    'primary key' => array('id_regione'),
    'indexes' => array(),
  );

  $schema['italy_stati'] = array(
    'fields' => array(
      //indici
      'id_stato'      => array('type' => 'char' , 'length' => 2, 'not null' => TRUE),
      'stato'      => array('type' => 'varchar', 'length' => 50,'not null' => TRUE, 'default' => ''),
    ),
    'primary key' => array('id_stato'),
    'indexes' => array(),
  );


  return $schema;
}
function italy_install() {
  $module_path = \Drupal::service('extension.list.module')->getPath('italy');
  $sql = file_get_contents($module_path . '/regioni.sql');
  \Drupal::database()->query("$sql");
  $sql = file_get_contents($module_path . '/province.sql');
  \Drupal::database()->query("$sql");
  $sql = file_get_contents($module_path . '/stati.sql');
  \Drupal::database()->query("$sql");
}


